export const quaTrinhLVHT = "Quá trình làm việc và học tập";
export const thamGiaToChucCT = "Tham gia các tổ chức chính trị, các hôị nghề nghiệp";
export const daoTao = "Đào tạo";
export const boiDuong = "Bồi dưỡng";
export const khenThuong = "Khen thưởng";
export const kyLuat = "Kỷ luật";
export const lichSuBanThan = "Lịch sử bản thân";
export const quanHeGiaDinh = "Quan hệ gia đình";
export const noiSinh_Step1 = "Nơi sinh"
export const queQuan_Step1 = "Quê quán"
export const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";
export const GET_PROVINCES = "GET_PROVINCES";
export const GET_DISTRICTS_BIRTH_PLACE = "GET_DISTRICTS_BIRTH_PLACE";
export const GET_DISTRICTS_HOME_TOWN = "GET_DISTRICTS_HOME_TOWN";
export const GET_DISTRICTS_ADDRESS = "GET_DISTRICTS_ADDRESS";
export const GET_DISTRICTS_HOKHAU = "GET_DISTRICTS_HOKHAU";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const ONLY_CREATE_PROFILE = "ONLY_CREATE_PROFILE";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_INFORMATION = "GET_USER_INFORMATION";
export const GET_DEP_POS = "GET_DEPARTMENT_POSITION";
export const GET_PART = "GET_PART";
export const GET_AVATAR = "GET_AVATAR";
export const DELETE_DEP_POS = "DELETE_DEP_POS";
export const GET_DEPARTMENT_LIST = "GET_DEPARTMENT_LIST";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const GET_DEPARTMENT_INFOR = "GET_DEPARTMENT_INFOR";
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";