import { checkMicroFe, getTokenInCookie } from "../ultils/helper";

export const TOKEN = getTokenInCookie();

// TOKEN ADMIN, NHÂN SỰ
// export const TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoyNzUwNDExMDg3fQ.uWeEJEXHyNysw85k22m0s6dFNi4nJFAO8NS8leY6fyA";
// TOKEN user
// export const TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZXhwIjoyNzUwNDY3MDkwfQ.jS2LpSrpCSosjuMLT1MJcuo1NIemmfv-hkqo4yciNy8"
export const local = checkMicroFe() === true ? "https://profileservice.tuoitre.vn" : ""


export const quaTrinhLVHT = "Quá trình làm việc và học tập";
export const thamGiaToChucCT = "Tham gia các tổ chức chính trị, các hôị nghề nghiệp";
export const daoTao = "Đào tạo";
export const boiDuong = "Bồi dưỡng";
export const khenThuong = "Khen thưởng";
export const kyLuat = "Kỷ luật";
export const lichSuBanThan = "Lịch sử bản thân";
export const quanHeGiaDinh = "Quan hệ gia đình";
export const noiSinh_Step1 = "Nơi sinh"
export const queQuan_Step1 = "Quê quán"
export const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";
export const GET_PROVINCES = "GET_PROVINCES";
export const GET_DISTRICTS_BIRTH_PLACE = "GET_DISTRICTS_BIRTH_PLACE";
export const GET_DISTRICTS_HOME_TOWN = "GET_DISTRICTS_HOME_TOWN";
export const GET_DISTRICTS_ADDRESS = "GET_DISTRICTS_ADDRESS";
export const GET_DISTRICTS_HOKHAU = "GET_DISTRICTS_HOKHAU";
export const GET_DISTRICTS_STEP8 = "GET_DISTRICTS_STEP8";
export const GET_DISTRICTS_STEP7 = "GET_DISTRICTS_STEP7";
export const GET_DISTRICTS_STEP9 = "GET_DISTRICTS_STEP9";
export const GET_DISTRICTS_STEP7_CON = "GET_DISTRICTS_STEP7_CON";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const ONLY_CREATE_PROFILE = "ONLY_CREATE_PROFILE";
export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_INFORMATION = "GET_USER_INFORMATION";
export const GET_DEP_POS = "GET_DEPARTMENT_POSITION";
export const GET_PART = "GET_PART";
export const GET_AVATAR = "GET_AVATAR";
export const DELETE_DEP_POS = "DELETE_DEP_POS";
export const GET_DEPARTMENT_LIST = "GET_DEPARTMENT_LIST";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const GET_DEPARTMENT_INFOR = "GET_DEPARTMENT_INFOR";
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const GET_POSITIONS_LIST = "GET_POSITIONS_LIST";
export const GET_POSITION_TYPE_LIST = "GET_POSITION_TYPE_LIST";
export const CREATE_POSITION_TYPE = "CREATE_POSITION_TYPE";
export const UPDATE_POSITION_TYPE = "UPDATE_POSITION_TYPE";
export const DELETE_POSITION_TYPE = "DELETE_POSITION_TYPE";
export const CREATE_POSITION_AND_MANAGEMENT = "CREATE_POSITION_AND_MANAGEMENT";
export const UPDATE_POSITION_AND_MANAGEMENT = "UPDATE_POSITION_AND_MANAGEMENT";
export const DELETE_POSITION_AND_MANAGEMENT = "DELETE_POSITION_AND_MANAGEMENT";
export const GET_PERSONAL_HISTORY = "GET_PERSONAL_HISTORY"
export const CREATE_PERSONAL_HISTORY = "CREATE_PERSONAL_HISTORY"
export const UPDATE_PERSONAL_HISTORY = "UPDATE_PERSONAL_HISTORY"
export const DELETE_PERSONAL_HISTORY = "DELETE_PERSONAL_HISTORY"
export const CREATE_PARTY = "CREATE_PARTY"
export const UPDATE_PARTY = "UPDATE_PARTY"
export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION"
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION"
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION"
export const CREATE_TRAINING = "CREATE_TRAINING"
export const UPDATE_TRAINING = "UPDATE_TRAINING"
export const DELETE_TRAINING = "DELETE_TRAINING"
export const CREATE_REWARD_DISCIPLINE = "CREATE_REWARD_DISCIPLINE"
export const DELETE_REWARD_DISCIPLINE = "DELETE_REWARD_DISCIPLINE"
export const UPDATE_REWARD_DISCIPLINE = "UPDATE_REWARD_DISCIPLINE"
export const CREATE_FAMILY_RELATIONSHIP = "CREATE_FAMILY_RELATIONSHIP"
export const UPDATE_FAMILY_RELATIONSHIP = "UPDATE_FAMILY_RELATIONSHIP"
export const GET_DEP_POS_TO_SEARCH = "GET_DEP_POS_TO_SEARCH"
export const SEARCH = "SEARCH"
export const GET_PROFILE_BY_USER_ID = "GET_PROFILE_BY_USER_ID"
export const GET_PROFILE_BY_TOKEN = "GET_PROFILE_BY_TOKEN"
export const UPDATE_PROFILE_ACTIVE = "UPDATE_PROFILE_ACTIVE"
export const GET_PERMISSION_LIST = "GET_PERMISSION_LIST"
export const CREATE_PERMISSION = "CREATE_PERMISSION"
export const UPDATE_PERMISSION = "UPDATE_PERMISSION"
export const DELETE_PERMISSION = "DELETE_PERMISSION"
export const GET_PERMISSION_POSITION = "GET_PERMISSION_POSITION"