export const userInforEmpty = {
        canCuocCD: "",
        chuyenMon: "",
        danToc: "",
        email: "",
        gioiTinh: 1,
        hoKhauThuongTru: {diaChi: '', huyen: '', quan: '', tinh: ''},
        hoTen: "",
        hocVan: "",
        lyLuanCT: "",
        ngayBoNhiem: "",
        ngayCapCCCD: "",
        ngayCapTheNhaBao: "",
        // ngayDuocTuyenDung: "21-07-2022",
        ngayHetHanBoNhiem: "",
        ngayThangNamSinh: "",
        ngheNghiep: "",
        ngoaiNgu: "",
        noiCapCCCD: "",
        noiOHienTai: {diaChi: '', huyen: '', quan: '', tinh: ''},
        noiSinh: {huyen: '', quan: '', tinh: ''},
        queQuan: {huyen: '', quan: '', tinh: ''},
        soDienThoai: "",
        soDienThoaiNoiBo: "",
        soTheNhaBao: "",
        phongBanCVObj: [],
        tenThuongGoi: "",
        theCoHieuLucDen: "",
        theCoHieuLucTu: "",
        tonGiao: "",
        thanhPhanXuatThan: '',
 }