export const userInforEmpty = {
        email: "",
        soDienThoai:"",
        chuyenMon: "",
        danToc: "",
        gioiTinh: "1",
        hoTen: "",
        hocVan: "",
        lyLuanCT: "",
        ngayThangNamSinh: "",
        maSoFake: "",
        ngayHetHanBoNhiem: "",
        ngayDuocTuyenDung: "",
        ngayBoNhiem: "",
        ngayXuatNgu: "",
        ngheNghiep: "",
        ngoaiNgu: "",
        noiOHienTai: {diaChi: "", huyen: "", quan: "", tinh: ""},
        noiSinh: {huyen: "", quan: "", tinh: ""},
        phongBanCVObj: [],
        queQuan: {huyen: "", quan: "", tinh: ""},
        soTruongCongTac: "",
        tenThuongGoi: "",
        toChucLamViec: "",
        tonGiao: "",
        theCoHieuLucTu: "",
        theCoHieuLucDen:"",
        thanhPhanXuatThan: "",
        to: "",
        hoKhauThuongTru: {diaChi: "",huyen: "",quan:"",tinh:""},
 }